apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: kui550822-go 
  janus-idp.io/tekton: kui550822-go
  backstage.io/kubernetes-id: kui550822-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: kui550822-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml