apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: kui550822-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: kui550822-go 
  name: kui550822-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: kui550822-go 
